title: "[Q&A] "
labels: ["q&a"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form so the community can better assist you!
  - type: input
    attributes:
      label: Python version
      description: Python version (can use `python3 -V`)
    validations:
      required: true
  - type: input
    attributes:
      label: NVFlare version
      description: NVFlare version (can use `python3 -m pip list | grep "nvflare"`)
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Operating system
      options:
        - Windows
        - Mac
        - Ubuntu
        - CentOS
        - Other
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Have you successfully run the following examples?
      options:
        - label: hello-numpy-sag with simulator
        - label: hello-pt with simulator
        - label: hello-numpy-sag with POC
        - label: hello-pt with POC
  - type: textarea
    id: questions
    attributes:
      label: Please describe your question
      description: "Please describe your question. It would be better if you can attach some logs."
      value: |
        I run into the following issue and don't know what to do ...
      render: bash
    validations:
      required: true
